### ISSUE TITLE
Weird compilation error on Route parsing

### ISSUE THREAD

**Issue by rcasula** [pointfreeco/swift-url-routing#50]
Hi, I was trying to model an existing API but I'm encountering a problem.

Example:

This is one of the urls: `BASE_URL/somepath/SOME_STRING_VAR/ANOTHER_STRING_VAR`.
The method is POST and it has a `String` body.

I was trying to model it like this:
```swift
enum SiteRoute {
    case somepath(var1: String, var2: String, body: String)
}
... 
let router = OneOf {
    Route(.case(SiteRoute.somepath)) {
        Method.post
        Path { 
            "someroute"
            Parse(.string)
            Parse(.string)
        }
        Body(?) // I can't figure out what to put here.
    }
}
```
If I define the model like this, instead:

```swift
enum SiteRoute {
    case somepath(var1: String, var2: String, body: SomeModel)
}
... 
let router = OneOf {
    Route(.case(SiteRoute.somepath)) {
        Method.post
        Path { 
            "someroute"
            Parse(.string)
            Parse(.string)
        }
        Body(.json(SomeModel.self))
    }
}
```
It throws me this compile error.
<img width="489" alt="Screenshot 2022-09-13 at 11 11 41" src="https://user-images.githubusercontent.com/16337140/189861759-d608d07d-1455-40bf-b5eb-996b938a4dde.png">

How can I solve this (theoretically shouldn't be) complicated task? I'm sure there's something I'm missing.
Thanks in advance.

**Comment by rcasula** [comment]
Anyone?

**Comment by mbrandonw** [comment]
Hi @rcasula, this is a bit of a gotcha with result builders, and hopefully it's something we can make a little bit nicer soon.

But the problem is that this kind of parser:

```swift
Path { 
  "someroute"
  Parse(.string)
  Parse(.string)
}
Body(.json(SomeModel.self))
```

…outputs a nested tuple of type `((String, String), SomeModel)`. The result builders can't automatically flatten that to `(String, String, SomeModel)`.

The easiest fix is to define a type that holds both strings so you can parse into a single type:

```swift
Path { 
  Parse(.memberwise(SomeStrings.init)) {
    "someroute"
    Parse(.string)
    Parse(.string)
  }
}
Body(.json(SomeModel.self))
```

That will give you a tuple of `(SomeStrings, SomeModel)`, and then that can be mapped into the enum case.

**Comment by rcasula** [comment]
It was simple and tricky at the same time, I guess I need to study more the parser's library. Thank you so much for your help!
